### ISSUE TITLE
Doxygen comments and documentation

### ISSUE THREAD

**Issue by Petross404** [dimitry-ishenko-cpp/gpio#6]
Hello friend, it's been a long time. I hope you are doing well.

In the last few weeks I am trying to gain interest again in programming with my Adafruit Ft232h and I find your gpio++ library interesting.

I am having trouble though to understand the API. I would like to put doxygen comments and create documentation for the API, but I don't know anything. Are you planning on creating a basic "wiki" or something besides the examples?

I am more than willing to help in something like this, so please let me know if I can help somehow.

Thank you very much.

**Comment by dimitry-ishenko** [comment]
I wasn't really planning any documentation. The library is pretty small is very self-explanatory.

I also haven't touched the project for several years. I might have another project coming up towards the end of the year, where I will have use for it and in that case I might spend the time to do updates, add documentation, etc.

**Comment by Petross404** [comment]
Ok, thank you. Good to know :)

**Comment by dimitry-ishenko** [comment]
@Petross404 if you have any questions about the library, feel free to ask.
